// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqmVGnGxGfkkkAqvy8v5-Bii3V9cySgWI',
    appId: '1:1093958609307:web:b7ef5e128d45d9ff5e593e',
    messagingSenderId: '1093958609307',
    projectId: 'todoapp-2b418',
    authDomain: 'todoapp-2b418.firebaseapp.com',
    storageBucket: 'todoapp-2b418.firebasestorage.app',
    measurementId: 'G-B9SHP2S4ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF7km8p2CW6IaQ8ErOg1g6Yftt4bai-VI',
    appId: '1:1093958609307:android:5f2c81d364ac3c985e593e',
    messagingSenderId: '1093958609307',
    projectId: 'todoapp-2b418',
    storageBucket: 'todoapp-2b418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEC-YkukKMrfXuFvEg75F1WCR4qW_JL5s',
    appId: '1:1093958609307:ios:e4b3124dda0ad0a55e593e',
    messagingSenderId: '1093958609307',
    projectId: 'todoapp-2b418',
    storageBucket: 'todoapp-2b418.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEC-YkukKMrfXuFvEg75F1WCR4qW_JL5s',
    appId: '1:1093958609307:ios:e4b3124dda0ad0a55e593e',
    messagingSenderId: '1093958609307',
    projectId: 'todoapp-2b418',
    storageBucket: 'todoapp-2b418.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqmVGnGxGfkkkAqvy8v5-Bii3V9cySgWI',
    appId: '1:1093958609307:web:8ac2b9b746f971835e593e',
    messagingSenderId: '1093958609307',
    projectId: 'todoapp-2b418',
    authDomain: 'todoapp-2b418.firebaseapp.com',
    storageBucket: 'todoapp-2b418.firebasestorage.app',
    measurementId: 'G-F59T4RLK2R',
  );
}
